--------------------------------------------------------
--  File created - Saturday-April-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASP_NET_ROLES
--------------------------------------------------------

  CREATE TABLE "ASP_NET_ROLES" 
   (	"ID" NVARCHAR2(450), 
	"NAME" NVARCHAR2(256), 
	"NORMALIZED_NAME" NVARCHAR2(256), 
	"CONCURRENCY_STAMP" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_ROLE_CLAIMS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_ROLE_CLAIMS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLE_ID" NVARCHAR2(450), 
	"CLAIM_TYPE" NVARCHAR2(2000), 
	"CLAIM_VALUE" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USERS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USERS" 
   (	"ID" NVARCHAR2(450), 
	"USER_NAME" NVARCHAR2(256), 
	"NORMALIZED_USER_NAME" NVARCHAR2(256), 
	"EMAIL" NVARCHAR2(256), 
	"NORMALIZED_EMAIL" NVARCHAR2(256), 
	"EMAIL_CONFIRMED" NUMBER(1,0), 
	"PASSWORD_HASH" NVARCHAR2(2000), 
	"SECURITY_STAMP" NVARCHAR2(2000), 
	"CONCURRENCY_STAMP" NVARCHAR2(2000), 
	"PHONE_NUMBER" NVARCHAR2(2000), 
	"PHONE_NUMBER_CONFIRMED" NUMBER(1,0), 
	"TWO_FACTOR_ENABLED" NUMBER(1,0), 
	"LOCKOUT_END" TIMESTAMP (7) WITH TIME ZONE, 
	"LOCKOUT_ENABLED" NUMBER(1,0), 
	"ACCESS_FAILED_COUNT" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_CLAIMS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_CLAIMS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NVARCHAR2(450), 
	"CLAIM_TYPE" NVARCHAR2(2000), 
	"CLAIM_VALUE" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_LOGINS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_LOGINS" 
   (	"LOGIN_PROVIDER" NVARCHAR2(128), 
	"PROVIDER_KEY" NVARCHAR2(128), 
	"PROVIDER_DISPLAY_NAME" NVARCHAR2(2000), 
	"USER_ID" NVARCHAR2(450)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_ROLES" 
   (	"USER_ID" NVARCHAR2(450), 
	"ROLE_ID" NVARCHAR2(450)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_TOKENS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_TOKENS" 
   (	"USER_ID" NVARCHAR2(450), 
	"LOGIN_PROVIDER" NVARCHAR2(128), 
	"NAME" NVARCHAR2(128), 
	"VALUE" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table DEVICE_CODES
--------------------------------------------------------

  CREATE TABLE "DEVICE_CODES" 
   (	"USER_CODE" NVARCHAR2(200), 
	"DEVICE_CODE" NVARCHAR2(200), 
	"SUBJECT_ID" NVARCHAR2(200), 
	"SESSION_ID" NVARCHAR2(100), 
	"CLIENT_ID" NVARCHAR2(200), 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATION_TIME" TIMESTAMP (7), 
	"EXPIRATION" TIMESTAMP (7), 
	"DATA" NCLOB
   ) ;
--------------------------------------------------------
--  DDL for Table PERSISTED_GRANTS
--------------------------------------------------------

  CREATE TABLE "PERSISTED_GRANTS" 
   (	"KEY" NVARCHAR2(200), 
	"TYPE" NVARCHAR2(50), 
	"SUBJECT_ID" NVARCHAR2(200), 
	"SESSION_ID" NVARCHAR2(100), 
	"CLIENT_ID" NVARCHAR2(200), 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATION_TIME" TIMESTAMP (7), 
	"EXPIRATION" TIMESTAMP (7), 
	"CONSUMED_TIME" TIMESTAMP (7), 
	"DATA" NCLOB
   ) ;
--------------------------------------------------------
--  DDL for Table __EFMigrationsHistory
--------------------------------------------------------

  CREATE TABLE "__EFMigrationsHistory" 
   (	"MigrationId" NVARCHAR2(150), 
	"ProductVersion" NVARCHAR2(32)
   ) ;
REM INSERTING into ASP_NET_ROLES
SET DEFINE OFF;
REM INSERTING into ASP_NET_ROLE_CLAIMS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USERS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_CLAIMS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_LOGINS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_ROLES
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_TOKENS
SET DEFINE OFF;
REM INSERTING into DEVICE_CODES
SET DEFINE OFF;
REM INSERTING into PERSISTED_GRANTS
SET DEFINE OFF;
REM INSERTING into "__EFMigrationsHistory"
SET DEFINE OFF;
Insert into "__EFMigrationsHistory" ("MigrationId","ProductVersion") values ('20220401024816_initial','5.0.15');
--------------------------------------------------------
--  DDL for Index EMAILINDEX
--------------------------------------------------------

  CREATE INDEX "EMAILINDEX" ON "ASP_NET_USERS" ("NORMALIZED_EMAIL") 
  ;
--------------------------------------------------------
--  DDL for Index IX_ASP_NET_ROLE_CLAIMS_ROLE_ID
--------------------------------------------------------

  CREATE INDEX "IX_ASP_NET_ROLE_CLAIMS_ROLE_ID" ON "ASP_NET_ROLE_CLAIMS" ("ROLE_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_ASP_NET_USER_CLAIMS_USER_ID
--------------------------------------------------------

  CREATE INDEX "IX_ASP_NET_USER_CLAIMS_USER_ID" ON "ASP_NET_USER_CLAIMS" ("USER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_ASP_NET_USER_LOGINS_USER_ID
--------------------------------------------------------

  CREATE INDEX "IX_ASP_NET_USER_LOGINS_USER_ID" ON "ASP_NET_USER_LOGINS" ("USER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_ASP_NET_USER_ROLES_ROLE_ID
--------------------------------------------------------

  CREATE INDEX "IX_ASP_NET_USER_ROLES_ROLE_ID" ON "ASP_NET_USER_ROLES" ("ROLE_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_DEVICE_CODES_DEVICE_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IX_DEVICE_CODES_DEVICE_CODE" ON "DEVICE_CODES" ("DEVICE_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index IX_DEVICE_CODES_EXPIRATION
--------------------------------------------------------

  CREATE INDEX "IX_DEVICE_CODES_EXPIRATION" ON "DEVICE_CODES" ("EXPIRATION") 
  ;
--------------------------------------------------------
--  DDL for Index IX_PERSISTED_GRANTS_EXPIRATION
--------------------------------------------------------

  CREATE INDEX "IX_PERSISTED_GRANTS_EXPIRATION" ON "PERSISTED_GRANTS" ("EXPIRATION") 
  ;
--------------------------------------------------------
--  DDL for Index IX_PERSISTED_GRANTS_SUBJECT_ID_CLIENT_ID_TYPE
--------------------------------------------------------

  CREATE INDEX "IX_PERSISTED_GRANTS_SUBJECT_ID_CLIENT_ID_TYPE" ON "PERSISTED_GRANTS" ("SUBJECT_ID", "CLIENT_ID", "TYPE") 
  ;
--------------------------------------------------------
--  DDL for Index IX_PERSISTED_GRANTS_SUBJECT_ID_SESSION_ID_TYPE
--------------------------------------------------------

  CREATE INDEX "IX_PERSISTED_GRANTS_SUBJECT_ID_SESSION_ID_TYPE" ON "PERSISTED_GRANTS" ("SUBJECT_ID", "SESSION_ID", "TYPE") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_ROLES" ON "ASP_NET_ROLES" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_ROLE_CLAIMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_ROLE_CLAIMS" ON "ASP_NET_ROLE_CLAIMS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_USERS" ON "ASP_NET_USERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_USER_CLAIMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_USER_CLAIMS" ON "ASP_NET_USER_CLAIMS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_USER_LOGINS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_USER_LOGINS" ON "ASP_NET_USER_LOGINS" ("LOGIN_PROVIDER", "PROVIDER_KEY") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_USER_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_USER_ROLES" ON "ASP_NET_USER_ROLES" ("USER_ID", "ROLE_ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ASP_NET_USER_TOKENS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASP_NET_USER_TOKENS" ON "ASP_NET_USER_TOKENS" ("USER_ID", "LOGIN_PROVIDER", "NAME") 
  ;
--------------------------------------------------------
--  DDL for Index PK_DEVICE_CODES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DEVICE_CODES" ON "DEVICE_CODES" ("USER_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index PK_PERSISTED_GRANTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PERSISTED_GRANTS" ON "PERSISTED_GRANTS" ("KEY") 
  ;
--------------------------------------------------------
--  DDL for Index PK___EFMigrationsHistory
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK___EFMigrationsHistory" ON "__EFMigrationsHistory" ("MigrationId") 
  ;
--------------------------------------------------------
--  DDL for Index ROLENAMEINDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLENAMEINDEX" ON "ASP_NET_ROLES" ("NORMALIZED_NAME") 
  ;
--------------------------------------------------------
--  DDL for Index USERNAMEINDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERNAMEINDEX" ON "ASP_NET_USERS" ("NORMALIZED_USER_NAME") 
  ;
--------------------------------------------------------
--  Constraints for Table ASP_NET_ROLES
--------------------------------------------------------

  ALTER TABLE "ASP_NET_ROLES" ADD CONSTRAINT "PK_ASP_NET_ROLES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_ROLES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_ROLE_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_ROLE_CLAIMS" ADD CONSTRAINT "PK_ASP_NET_ROLE_CLAIMS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  --ALTER TABLE "ASP_NET_ROLE_CLAIMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_ROLE_CLAIMS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USERS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USERS" ADD CONSTRAINT "PK_ASP_NET_USERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("EMAIL_CONFIRMED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("PHONE_NUMBER_CONFIRMED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("TWO_FACTOR_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("LOCKOUT_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("ACCESS_FAILED_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_CLAIMS" ADD CONSTRAINT "PK_ASP_NET_USER_CLAIMS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  --ALTER TABLE "ASP_NET_USER_CLAIMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_CLAIMS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_LOGINS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_LOGINS" ADD CONSTRAINT "PK_ASP_NET_USER_LOGINS" PRIMARY KEY ("LOGIN_PROVIDER", "PROVIDER_KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_LOGINS" MODIFY ("LOGIN_PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_LOGINS" MODIFY ("PROVIDER_KEY" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_LOGINS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_ROLES" ADD CONSTRAINT "PK_ASP_NET_USER_ROLES" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_TOKENS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_TOKENS" ADD CONSTRAINT "PK_ASP_NET_USER_TOKENS" PRIMARY KEY ("USER_ID", "LOGIN_PROVIDER", "NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_TOKENS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_TOKENS" MODIFY ("LOGIN_PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_TOKENS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICE_CODES
--------------------------------------------------------

  ALTER TABLE "DEVICE_CODES" ADD CONSTRAINT "PK_DEVICE_CODES" PRIMARY KEY ("USER_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "DEVICE_CODES" MODIFY ("USER_CODE" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("DEVICE_CODE" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("EXPIRATION" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSISTED_GRANTS
--------------------------------------------------------

  ALTER TABLE "PERSISTED_GRANTS" ADD CONSTRAINT "PK_PERSISTED_GRANTS" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table __EFMigrationsHistory
--------------------------------------------------------

  ALTER TABLE "__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
  USING INDEX  ENABLE;
  ALTER TABLE "__EFMigrationsHistory" MODIFY ("MigrationId" NOT NULL ENABLE);
  ALTER TABLE "__EFMigrationsHistory" MODIFY ("ProductVersion" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASP_NET_ROLE_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_ROLE_CLAIMS" ADD CONSTRAINT "FK_ASP_NET_ROLE_CLAIMS_ASP_NET_ROLES_ROLE_ID" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ASP_NET_ROLES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASP_NET_USER_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_CLAIMS" ADD CONSTRAINT "FK_ASP_NET_USER_CLAIMS_ASP_NET_USERS_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "ASP_NET_USERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASP_NET_USER_LOGINS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_LOGINS" ADD CONSTRAINT "FK_ASP_NET_USER_LOGINS_ASP_NET_USERS_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "ASP_NET_USERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASP_NET_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_ROLES" ADD CONSTRAINT "FK_ASP_NET_USER_ROLES_ASP_NET_ROLES_ROLE_ID" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ASP_NET_ROLES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ASP_NET_USER_ROLES" ADD CONSTRAINT "FK_ASP_NET_USER_ROLES_ASP_NET_USERS_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "ASP_NET_USERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASP_NET_USER_TOKENS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_TOKENS" ADD CONSTRAINT "FK_ASP_NET_USER_TOKENS_ASP_NET_USERS_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "ASP_NET_USERS" ("ID") ON DELETE CASCADE ENABLE;
